version: "3"

services:
  nodeosd:
    image: qiuqi830/eos-mainnet:1.6.0
    command: /opt/eosio/bin/nodeos --data-dir=/data --config-dir=/etc/nodeos
    hostname: nodeosd
    ports:
      - 8890:8888
      - 9878:9876
    expose:
      - "8888"
    volumes:
      - /volume2/EOS/nodeos-data-volume/nodeos-data-eosmainnet/config:/etc/nodeos
      - /volume2/EOS/nodeos-data-volume/nodeos-data-eosmainnet/data:/data